export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET'

export const EMAIL_SEND_REQUEST = 'EMAIL_SEND_REQUEST'
export const EMAIL_SEND_SUCCESS = 'EMAIL_SEND_SUCCESS'
export const EMAIL_SEND_FAIL = 'EMAIL_SEND_FAIL'
export const EMAIL_RESET = 'EMAIL_RESET'
